CREATE TABLE IF NOT EXISTS table1
(
	id INTEGER NOT NULL UNIQUE,
	name VARCHAR(50),
	age INTEGER
);

INSERT INTO table1 VALUES(1, 'Iron Man', 20);
INSERT INTO table1 VALUES(2, 'Black Widow', 21);
INSERT INTO table1 VALUES(3, 'Captain America', 22);
